require("plugins.plugins-setup")
require("core.options")
require("core.keymaps")

-- 插件
require("plugins.lualine")
require("plugins/nvim-tree")
require("plugins/nvim-treesitter")
require("plugins/lsp")
require("plugins/cmp")
require("plugins/go-nvim")
require("plugins/rust-nvim")
require("plugins/bufferline")
require("plugins/gitsigns")
require("plugins/telescope")
require("plugins/comment")
require("plugins/autopairs")
require("plugins/fterm")
require("plugins/dap")

